### ISSUE TITLE
"Gemini" name?

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/Twinroom#12]
I find the name Gemini an incovenient choice, as Gemini is Google's AI (which we may end up using?) as well as 100.000 other things...
What about:
- Doubleroom
- Goroom
- Twinroom
- Allroom
- ZenTwin
- Twincode
...

?

**Comment by adam-burns** [comment]
janus (2 faced god of thresholds)
legba (voodoo trickster god of crossroads)
